import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";

const manrope = localFont({
  src: [
    {
      path: "../../public/fonts/manrope.bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/manrope.semibold.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/manrope.regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/manrope.thin.woff",
      weight: "100",
      style: "normal",
    },
  ],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
